name: Publish on Modrinth

on: [ pull_request, workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.21
  JAVA_VERSION: 21

permissions:
   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Envrionment Variables
        run: env

      - name: Checkout Repsitory
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Modrinth)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: "bUHfVbsa"
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
